-- 大学マスタと過去問セットの投入。0001 と 0002 を流したあとに実行する。
--
-- このファイルは scripts/gen-seed-sql.ts が catalog.ts から生成する。手で編集しない。
-- 中身を変えるときは src/data/catalog.ts を直して npm run gen:seed。
--
-- 何度実行しても同じ結果になる（既にある行は更新される）。
-- universities: 10件 / exam_sets: 273件

insert into universities (id, name, short_name, default_weight, sort_order) values
  ('kyoto', '京都大学', '京大', 10, 1),
  ('tokyo', '東京大学', '東大', 4, 2),
  ('osaka', '大阪大学', '阪大', 4, 3),
  ('science-tokyo', '東京科学大学（旧 東京工業大学）', '科学大', 4, 4),
  ('tohoku', '東北大学', '東北大', 2, 5),
  ('nagoya', '名古屋大学', '名大', 2, 6),
  ('kyushu', '九州大学', '九大', 2, 7),
  ('hokkaido', '北海道大学', '北大', 2, 8),
  ('waseda', '早稲田大学', '早大', 1, 9),
  ('keio', '慶應義塾大学', '慶大', 1, 10)
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  default_weight = excluded.default_weight,
  sort_order = excluded.sort_order;

insert into exam_sets (university_id, faculty, year, curriculum, subject, subject_label, duration_min, question_count, question_points, total_points, has_solution, access_url, source_url) values
  ('kyoto', '工学部', 2005, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2006, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2007, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2008, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2009, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2010, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2011, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2012, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2013, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2014, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2015, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2016, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2017, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2018, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2019, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2020, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2021, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2022, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2023, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2024, 'old', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2025, 'new', 'math', '数学（理系）', 150, 6, null, 200, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/rikeisuugaku/'),
  ('kyoto', '工学部', 2005, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2006, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2007, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2008, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2009, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2010, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2011, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2012, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2013, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2014, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2015, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2016, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2017, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2018, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2019, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2020, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2021, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2022, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2023, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2024, 'old', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2025, 'new', 'english', '英語', 120, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/eigo/'),
  ('kyoto', '工学部', 2005, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2006, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2007, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2008, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2009, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2010, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2011, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2012, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2013, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2014, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2015, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2016, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2017, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2018, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2019, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2020, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2021, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2022, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2023, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2024, 'old', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2025, 'new', 'physics', '物理', 90, 3, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://www.zkai.co.jp/kyodai-exam/bunseki/butsuri/'),
  ('kyoto', '工学部', 2005, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2006, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2007, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2008, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2009, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2010, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2011, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2012, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2013, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2014, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2015, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2016, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2017, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2018, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2019, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2020, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2021, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2022, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2023, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2024, 'old', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('kyoto', '工学部', 2025, 'new', 'chemistry', '化学', 90, 4, null, null, false, 'https://www.kyoto-u.ac.jp/ja/admissions/undergrad/past-eq', 'https://ja.wikibooks.org/wiki/%E4%BA%AC%E5%A4%A7%E5%AF%BE%E7%AD%96/%E7%90%86%E7%A7%91'),
  ('tokyo', '理科', 2005, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2006, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2007, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2008, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2009, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2010, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2011, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2012, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2013, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2014, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2015, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2016, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2017, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2018, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2019, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2020, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2021, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2022, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2023, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2024, 'old', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('tokyo', '理科', 2025, 'new', 'math', '数学（理系）', 150, 6, null, 120, false, 'https://www.u-tokyo.ac.jp/ja/admissions/undergraduate/e01_07_25.html', 'https://www2.sundai.ac.jp/sokuhou/assets/pdf/tky1_suu2_2.pdf'),
  ('osaka', '理・工・基礎工', 2005, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2006, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2007, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2008, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2009, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2010, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2011, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2012, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2013, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2014, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2015, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2016, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2017, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2018, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2019, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2020, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2021, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2022, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2023, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2024, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('osaka', '理・工・基礎工', 2025, 'new', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/84'),
  ('science-tokyo', '理工学系', 2005, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2006, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2007, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2008, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2009, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2010, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2011, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2012, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2013, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2014, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2015, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2016, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2017, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2018, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2019, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2020, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2021, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2022, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2023, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2024, 'old', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('science-tokyo', '理工学系', 2025, 'new', 'math', '数学', 180, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://teambancho.com/titech-math/'),
  ('tohoku', '理系', 2005, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2006, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2007, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2008, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2009, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2010, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2011, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2012, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2013, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2014, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2015, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2016, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2017, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2018, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2019, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2020, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2021, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2022, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2023, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2024, 'old', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('tohoku', '理系', 2025, 'new', 'math', '数学（理系）', 150, 6, null, null, false, 'https://www.toshin-kakomon.com/', 'https://akahon.net/blog/90'),
  ('nagoya', '理系', 2005, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2006, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2007, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2008, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2009, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2010, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2011, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2012, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2013, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2014, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2015, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2016, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2017, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2018, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2019, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2020, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2021, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2022, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2023, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2024, 'old', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('nagoya', '理系', 2025, 'new', 'math', '数学（理系）', 150, 4, null, null, false, 'https://www.toshin-kakomon.com/', 'https://rikei-sora.com/nagoyadai-rikei-math-taisaku/'),
  ('kyushu', '理系', 2005, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2006, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2007, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2008, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2009, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2010, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2011, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2012, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2013, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2014, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2015, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2016, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2017, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2018, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2019, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2020, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2021, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2022, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2023, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2024, 'old', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('kyushu', '理系', 2025, 'new', 'math', '数学（理系）', 150, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://ryubunnkai.com/kyudai-math-trend-difficulty/'),
  ('hokkaido', '理系', 2005, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2006, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2007, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2008, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2009, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2010, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2011, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2012, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2013, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2014, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2015, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2016, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2017, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2018, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2019, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2020, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2021, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2022, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2023, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2024, 'old', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('hokkaido', '理系', 2025, 'new', 'math', '数学（理系）', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://jyuke-labo.com/daigakujyukentaisaku/hokkaidodaigaku/suugaku/'),
  ('waseda', '基幹理工学部', 2005, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2006, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2007, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2008, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2009, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2010, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2011, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2012, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2013, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2014, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2015, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2016, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2017, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2018, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2019, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2020, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2021, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2022, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2023, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2024, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('waseda', '基幹理工学部', 2025, 'new', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://logicalteacher.com/post-4273/4273/'),
  ('keio', '理工学部', 2005, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2006, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2007, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2008, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2009, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2010, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2011, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2012, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2013, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2014, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2015, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2016, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2017, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2018, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2019, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2020, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2021, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2022, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2023, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2024, 'old', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html'),
  ('keio', '理工学部', 2025, 'new', 'math', '数学', 120, 5, null, null, false, 'https://www.toshin-kakomon.com/', 'https://hiraocafe.com/exam/keio_rikou.html')
on conflict (university_id, faculty, year, subject) do update set
  curriculum = excluded.curriculum,
  subject_label = excluded.subject_label,
  duration_min = excluded.duration_min,
  question_count = excluded.question_count,
  question_points = excluded.question_points,
  total_points = excluded.total_points,
  has_solution = excluded.has_solution,
  access_url = excluded.access_url,
  source_url = excluded.source_url;

-- 確認用。大学ごとの件数が出れば成功
select u.short_name, count(*) as sets
  from exam_sets e join universities u on u.id = e.university_id
 group by u.short_name, u.sort_order
 order by u.sort_order;
